mv RpiRoadbook_English.po locales/en/LC_MESSAGES/rpiroadbook.po
mv RpiRoadbook_English.mo locales/en/LC_MESSAGES/rpiroadbook.mo
mv RpiRoadbook_French.po locales/fr/LC_MESSAGES/rpiroadbook.po
mv RpiRoadbook_French.mo locales/fr/LC_MESSAGES/rpiroadbook.mo
mv RpiRoadbook_Italian.po locales/it/LC_MESSAGES/rpiroadbook.po
mv RpiRoadbook_Italian.mo locales/it/LC_MESSAGES/rpiroadbook.mo
mv RpiRoadbook_German.po locales/de/LC_MESSAGES/rpiroadbook.po
mv RpiRoadbook_German.mo locales/de/LC_MESSAGES/rpiroadbook.mo
mv RpiRoadbook_Spanish.po locales/es/LC_MESSAGES/rpiroadbook.po
mv RpiRoadbook_Spanish.mo locales/es/LC_MESSAGES/rpiroadbook.mo
mv static_English.po static/locales/en/LC_MESSAGES/static.po
mv static_English.mo static/locales/en/LC_MESSAGES/static.mo
mv static_French.po static/locales/fr/LC_MESSAGES/static.po
mv static_French.mo static/locales/fr/LC_MESSAGES/static.mo
mv static_Italian.po static/locales/it/LC_MESSAGES/static.po
mv static_Italian.mo static/locales/it/LC_MESSAGES/static.mo
mv static_German.po static/locales/de/LC_MESSAGES/static.po
mv static_German.mo static/locales/de/LC_MESSAGES/static.mo
mv static_Spanish.po static/locales/es/LC_MESSAGES/static.po
mv static_Spanish.mo static/locales/es/LC_MESSAGES/static.mo