#!/bin/sh
### BEGIN INIT INFO
# Provides:          RpiRoadbook
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Derouleur de Roadook sous Rpi
# Description:       Derouleur de Roadook sous Rpi
### END INIT INFO

do_start () {
    cd /home/rpi/RpiRoadbook
    python RpiRoadbook.py &
}

case "$1" in

    start|"")
        do_start
        ;;

    restart|reload|force-reload)
        echo "Error: argument '$1' not supported">&2
        exit 3
        ;;

    stop)
        # No-op
        ;;

    status)
        exit 0
        ;;

    *)
        echo "Usage: /etc/init.d/S90RpiRoadbook {start|stop}">&2
        exit 3
        ;;

esac

:

